[package]
name = "clank"
version = "0.1.0"
authors = ["Paul Warner <paul.eliot.warner@gmail.com>"]
edition = "2018"

[[bin]]
name = "luatest"
path = "src/bin/luatest.rs"

[[bin]]
name = "drain"
path = "src/bin/drain.rs"

[dependencies]
specs = "0.14.3"
rand = "0.6.5"
log = "0.4.6"
fern = "0.5"
chrono = "0.4.6"
vulkano = "0.11.1"
vulkano-win = "0.11.1"
winit = "0.18"
image = "0.21.1"
vulkano-shaders = "0.11.1"
lazy_static = "1.3.0"
rusttype = "0.7.6"
rlua = "0.16.3"