[package]
name = "drain"
version = "0.1.0"
authors = ["Paul Warner <paul.eliot.warner@gmail.com>"]
edition = "2018"

[dependencies]
specs = "0.14.3"
rand = "0.6.5"
log = "0.4.6"
fern = "0.5"
chrono = "0.4.6"